### ISSUE TITLE
ESLint plugin doesn’t work with Yarn PnP in VSCode

### ISSUE THREAD

**Issue by lensbart** [microsoft/tsdoc#285]
Hello!

Not sure what’s causing the issue, I just see from the output dialog window that there was an error loading the plugin:

```
[Info  - 7:23:52 PM] ESLint server is starting
[Info  - 7:23:52 PM] ESLint server running in node v12.18.3
[Info  - 7:23:52 PM] ESLint server is running.
[Info  - 7:23:52 PM] ESLint library loaded from: codebase/.yarn/sdks/eslint/lib/api.js
(node:82068) UnhandledPromiseRejectionWarning: Error: Failed to load config "eslint-plugin-tsdoc" to extend from.
Referenced from: codebase/.eslintrc.json
    at configInvalidError (codebase/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (codebase/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (codebase/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (codebase/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (codebase/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (codebase/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (codebase/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (codebase/.yarn/cache/@eslint-eslintrc-npm-0.4.0-901e1408cc-d3f51b7419.zip/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
```

Other plugins are working fine and my editor is correctly configured for Yarn PnP as per [their instructions](https://next.yarnpkg.com/getting-started/editor-sdks#vscode).

**Comment by lensbart** [comment]
Not sure what changed, but I can’t reproduce the issue anymore.
